### ISSUE TITLE
Stylesheet system needs to be updated

### ISSUE THREAD

**Issue by Wolfmyths** [Wolfmyths/Genshin-Stopwatch#12]
A new stylesheet rework was just put into place. We need more color palette options (Color palette for each element in Genshin Impact) which can easily be done through an addition to a dictionary in `style.py -> __init__() -> self.colorPallets` there are some comments there to help.

My color theory isn't great so I was hoping someone could help me out with choosing the colors. If you have good suggestions for color pallets please say so in this thread.

One more thing I need done is that not every stylesheet was implemented into `style.py` like `countdown` in `addStopWatch()`. Because of this their stylesheets won't update correctly.

**Comment by Wolfmyths** [comment]
I also would like the light theme to be slightly darker, its too bright

**Comment by H4ppy-04** [comment]
> My color theory isn't great so I was hoping someone could help me out with choosing the colors. If you have good suggestions for color pallets please say so in this thread.

I'm pretty garbage at art in general but the [lospec palette list](https://lospec.com/palette-list) has some pretty good stuff.

**Comment by Wolfmyths** [comment]
Update: The stylesheets are fixed the only thing needed left are more/better color pallets

**Comment by H4ppy-04** [comment]
> 

Nice :muscle:

It's like 2 am for me, what timezone are you working in?

**Comment by Wolfmyths** [comment]
EST, currently 12PM for me, this issue should be closed pretty soon I'm really liking this website you showed me
