### ISSUE TITLE
style.py needs some cleanup

### ISSUE THREAD

**Issue by Wolfmyths** [Wolfmyths/Genshin-Stopwatch#14]
There are lines of code in `style.py` that need to be shorted or formatted differently.

For example:
`self.stopwatchStyleSheet_formatted = self.stopwatchStyleSheet.format(self.colorPallets[self.selectedColorPallet][0], self.colorPallets[self.selectedColorPallet][1], self.colorPallets[self.selectedColorPallet][2], self.colorPallets[self.selectedColorPallet][3], self.colorPallets[self.selectedColorPallet][4], self.stopwatchBorderColor)`

Yes. this is a single line of code lol.

**Comment by squireaa** [comment]
I will work on this.
