### ISSUE TITLE
Auto installer instead of providing a link

### ISSUE THREAD

**Issue by Wolfmyths** [Wolfmyths/Genshin-Stopwatch#19]
When Genshin Stopwatch detects a new update, it will prompt a link to the latest release page.

I was wondering if there was a way to download the release, unzip, replace it with the current executable, and then delete what's left of the `.zip` since that's all that's needed in order to update.

We also need to take account the platform the user is using, as there are MacOS/Linux versions as well

**Comment by ctrleo** [comment]
(to clarify on my last comment, I meant which branch should I work on, not fork)

**Comment by ghost** [comment]
this is resolved, we can close this issue now :p
